### ISSUE TITLE
Circular button animations are not working

### ISSUE THREAD

**Issue by szabee994** [mario-aleo/cordova-angular-angularMaterial-seed#5] opened 2016-06-15 08:22 UTC
I've just bulid my application using this seed, and everything is pretty okay, except the animations. The shadow animations are working fine but the circular reveal animation of button and some other animations of other elements just not working at all. I just ran out of ideas. I git cloned the seed to see am I messed up something but the animations haven't worked in the empty seed too.

**Comment by mario-aleo** [comment] 2016-06-15 14:14
Hey there,
I'd looked around to see what was going on, and I've found that I did had made a change on the angular-material.css on the wrong class.
I was just about to update the libs, and now that I did it, you can update to this new version of the seed and everything will work fine.
As soon as you see if the problem is solved, please do not forget to give me a feedback and close the issue.

Thanks for the support.

**Comment by szabee994** [comment] 2016-06-15 14:19
Hey! I've just solved the problem by using another libraries, and also I made some modification in the structure of the index.html for my project, but I'll clone the repo later and will try to run to see is it working now. :)

**Closed as completed** 2016-06-24 11:52 UTC
